### ISSUE TITLE
Android Java quick start still doesn't quite work

### ISSUE THREAD

**Issue by chalin** [grpc/grpc.io#321]
Even once #320 is merged, following the quick start instructions eventually results in the following error when I try to rebuild and reinstall the updated client app:

```console
examples > (cd android/helloworld; ../../gradlew installDebug)

> Configure project :app
The com.google.protobuf plugin was already applied to the project: :app and will not be applied again after plugin: android
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Task :app:compileDebugJavaWithJavac FAILED
/Users/chalin/tmp/grpc-java-tmp-v1.30.1/examples/android/helloworld/app/src/main/java/io/grpc/helloworldexample/HelloworldActivity.java:104: error: cannot find symbol
        HelloReply reply = stub.sayHelloAgain(request);
                               ^
  symbol:   method sayHelloAgain(HelloRequest)
  location: variable stub of type GreeterBlockingStub
1 error

FAILURE: Build failed with an exception.
```

This step happens after I've updated the proto, server code and client (Android and non-Android / desktop) code. I'm able to successfully run the updated server and updated (non-Android / desktop) client.

It seems that the Android client code isn't finding the updated protoc-generated files.

@ejona86 @voidzcy @creamsoup - thoughts?

**Comment by ejona86** [comment]
Make sure you modify the correct copy of helloworld.proto. The app has its own copy.

**Comment by chalin** [comment]
Ah! That'll do it, thanks!

**Comment by chalin** [comment]
@ejona86 - is there any way that the two examples could work from the same `.proto` source file? (I suspect that the answer is either "no" or "it would be complicated", but I figured that it is worth asking.)

**Comment by ejona86** [comment]
It is totally possible, but "it would be complicated," as in we'd have to plumb things in non-standard ways (protos are generally expected to be in src/main/proto) or make a library that is built separately. Nothing that lends itself well to an example.

**Comment by chalin** [comment]
Thanks for confirming.
